// <auto-generated/>
using System.Reflection;

[assembly: AssemblyFileVersionAttribute("1.0")]
[assembly: AssemblyVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
