// <auto-generated/>
using System.Reflection;

[assembly: AssemblyFileVersionAttribute("1.1.0")]
[assembly: AssemblyVersionAttribute("1.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyFileVersion = "1.1.0";
        internal const System.String AssemblyVersion = "1.1.0";
    }
}
